runtime: python37

entrypoint: gunicorn -b :$PORT backend.wsgi

beta_settings:
    cloud_sql_instances: clouds-258120:us-central1:cloud-db

runtime_config:
  python_version: 3

handlers:

- url: /static
  static_dir: static
- url: /.*
  script: auto