# Generated by Django 2.2.3 on 2019-10-22 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousFlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_flight', models.DateTimeField()),
                ('come_from', models.CharField(max_length=15)),
                ('come_to', models.CharField(max_length=15)),
                ('flight', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=15)),
                ('come_from', models.CharField(max_length=15)),
                ('come_to', models.CharField(max_length=15)),
                ('avia_company', models.CharField(max_length=15)),
                ('speed', models.FloatField()),
                ('registration_info', models.CharField(max_length=15)),
                ('flight_distance', models.IntegerField()),
                ('previous_routes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.PreviousFlights')),
            ],
        ),
    ]
