# Generated by Django 2.2.3 on 2019-10-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=15)),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('come_from', models.CharField(max_length=15)),
                ('come_to', models.CharField(max_length=15)),
                ('avia_company', models.CharField(max_length=15)),
                ('speed', models.FloatField()),
                ('registration_info', models.CharField(max_length=15)),
                ('flight_distance', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='previousflights',
            old_name='flight',
            new_name='flight_of_previous',
        ),
        migrations.DeleteModel(
            name='Plane',
        ),
        migrations.AddField(
            model_name='flight',
            name='previous_flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.PreviousFlights'),
        ),
    ]
