# Generated by Django 2.2.3 on 2019-10-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0002_auto_20191023_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='previous_flight',
        ),
        migrations.AddField(
            model_name='previousflights',
            name='previous_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plane.Flight'),
        ),
    ]
