# Generated by Django 2.2.3 on 2019-10-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0003_auto_20191023_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plane.Flight')),
            ],
        ),
        migrations.DeleteModel(
            name='PreviousFlights',
        ),
    ]
