# Generated by Django 2.2.3 on 2019-10-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0004_auto_20191023_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flight',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='start',
        ),
        migrations.RemoveField(
            model_name='history',
            name='name',
        ),
        migrations.AddField(
            model_name='history',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
