# Generated by Django 2.2.3 on 2019-11-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0005_auto_20191023_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='avia_company',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='come_from',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='come_to',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='registration_info',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
